### PR TITLE
Feature expand tree

### LINKED ISSUE #28: Expand categories
As a  user I want to see all categories expanded whenever I open a new exploration view. This allows me a quicker overview and selection of the possible methods.

### PR DESCRIPTION
**Pull request by taminob**

### CODE REVIEW

**Comment by taminob** [comment]
close #28

**Review by sinahenning — COMMENTED** [review]
top

**Review by Zyranix — CHANGES_REQUESTED** [review]
In your test, you don't test if the tree morph is already expanded right after construction if you call expandRoots manually. Instead, you test if expandRoots work, which shouldn't be the goal.

**Comment by taminob** [comment]
> In your test, you don't test if the tree morph is already expanded right after construction if you call expandRoots manually. Instead, you test if expandRoots work, which shouldn't be the goal.

The expandRoots call there is actually just a debugging artifact. Should be fixed now

**Review by Zyranix — APPROVED** [review]
Looks fine now

**Pull request merged**
