### PR TITLE
Bugfix method selection update

### LINKED ISSUE #43: Selected methods aren't deselected when switching morph
If you chose some methods in the exploration view to apply on a morph, then change this morph to another one in the morph list, then the methods you chose were neither deselected nor updated the code box.

### LINKED ISSUE #55: changing morph doesnt update method selection
As a user I want to have the bug fixed that the list of available methods updates its selection when changing the morph.

### PR DESCRIPTION
**Pull request by Zyranix**
We really have no idea how to test this because #changeCurrentMorph calls updatePlaygroundContents which calls openInWorld, but this seems to only work if the explorationView instance is visually existing because it always throws an error with an undefined pasteup-morph (although the playground-pasteupmorph seems to exist).
We commented the test out in its current version, but we will merge anyway.

### CODE REVIEW

**Comment by Zyranix** [comment]
Why is trunk failing before it can even test? I don't think it's our fault.

**Review by sinahenning — APPROVED** [review]
Top

**Comment by taminob** [comment]
> We really have no idea how to test this because #changeCurrentMorph calls updatePlaygroundContents which calls openInWorld, but this seems to only work if the explorationView instance is visually existing because it always throws an error with an undefined pasteup-morph (although the playground-pasteupmorph seems to exist).
> We commented the test out in its current version, but we will merge anyway.

You might want to have a look at e.g. testAcceptDroppingMorph in #60 - we fixed this issue there by opening the instance (also done in the button test in overview) and closing it afterwards (that's actually still missing in the test in overview).

> Why is trunk failing before it can even test? I don't think it's our fault.

I reran the tests, doesn't fix it. No idea what's wrong.

**Comment by Zyranix** [comment]
Hm, tests seem to work now (there were also failing tests). I'll open an issue for the missing test.

**Pull request merged**
